spring.application.name=LinkShortener

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

spring.flyway.enabled=true

spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

app.validation.url-max-length=2048
app.validation.text-max-length=50000

app.shortcode.prefix=~